default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  # The database host. Defaults to localhost.
  host: localhost

development:
  <<: *default
  database: todo_list_app_development

test:
  <<: *default
  database: todo_list_app_test

production:
  primary: &primary_production
    <<: *default
    database: todo_list_app_production
    username: todo_list_app
    password: <%= ENV["TODO_LIST_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: todo_list_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: todo_list_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: todo_list_app_production_cable
    migrations_paths: db/cable_migrate
